language: node_js
node_js:
- node
- lts/*
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: npm release
      node_js: node
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: philippe.j.roy@gmail.com
        api_key:
          secure: hC93XR7oresvi3o7lGdfo7Jgi3BH09NV2I4WCWmO3E/iBgu2LNA4vP97AgiHzMBkyVSEs2fu+0BAqqeOc9CLC4cdC4JpC8TCKD8B+/qu8rQXXh7Q8KwQMhxkKM2T9CzuFUGMSXYBvy7kW2cmf8BWJ/wKJ9ucOj7MTN4jOVc5vv1cR+mULCJEy9Xqa1hlyay+3JBPZcZxVwIIUBFILq/Qf+4oXD98p0vmE77rWmCB2gN425ZfbCTucVI1HRzzaBbm74VuwpAuyLr36qRRwZjU8ZwOAEjrGCKdKQ/09e0ntchLgeId83Rv3B2jA7oY3qdrON0QibneY4tYsVnnYPWBNWwGB22Su2VouKUo8g04FeF+7vvrrNJCauloL/iaWXyjK95jrribJbPtSSdKX4nT8nX9D1xzoKkNlm1K1n72wCL1f6d+c5DCxJImcRV+mKN5OFy4QxmFwUhxvLLFaNSICm334bnxshJF8WEwURAsLcenAFFSmTGFeceVBWE4k0CYNlegQeVe/cLW1OWpQipwa0d6EEcXDO1wTtji4X75HO76awy02HQEaZRN+/hthXqi12TjGRvw7y6qsJj3u/Yf4k3W8nXBBPw7WvL6pngr//DOVLVa/NWcHddoy8dhENykQP2Wg2dG13Nfh394nS407Ch8xY8kG5JBZwpZFazbG7M=
        on: master
